# Generated by Django 2.1.1 on 2018-10-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181006_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isInGame',
            field=models.BooleanField(default=False),
        ),
    ]
